"""Adicionar colunas exercicios, dificuldades, divertido

Revision ID: f34171f817da
Revises: 
Create Date: 2024-06-18 16:36:59.823485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34171f817da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercicios', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('dificuldades', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('divertido', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('divertido')
        batch_op.drop_column('dificuldades')
        batch_op.drop_column('exercicios')

    # ### end Alembic commands ###
